spring.application.name=springbootdemo
server.port=8090

# For MySQL / PostgreSQL / Oracle (example for MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/employeedemodb
spring.datasource.username=root
spring.datasource.password=Shravan@1234567
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#jpa/hibernate properties
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Swagger properties
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#9. Mail Configuration
#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=your-email@gmail.com
#spring.mail.password=your-password
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

#11. Actuator Endpoints (Monitoring)
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always

#
#Profiles (Dev, Prod, etc.)
#spring.profiles.active=dev